package com.spring.mti.model.address;

// Generated 25.03.2013 20:11:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.transaction.annotation.Transactional;

import com.sun.istack.internal.NotNull;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name = "city")
public class City implements java.io.Serializable {
	@Id
	private long id;
	@NotNull
	private String name;
	@ManyToOne(cascade=CascadeType.REFRESH,fetch=FetchType.EAGER)
	@JoinColumn(name="countryid")
	private Country fk_country;
	@ManyToOne(cascade=CascadeType.REFRESH,fetch=FetchType.EAGER)
	@JoinColumn(name="regionid")
	private Region fk_region;
	
	public long getId() {
		return id;
	}
	
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public Country getFk_country() {
		return fk_country;
	}
	public void setFk_country(Country fk_country) {
		this.fk_country = fk_country;
	}
	public Region getFk_region() {
		return fk_region;
	}
	public void setFk_region(Region fk_region) {
		this.fk_region = fk_region;
	}

	/*
	private long id;
	private long countryid;
	private long regionid;
	private String name;

	public City() {
	}

	public City(long id, long countryid, long regionid, String name) {
		this.id = id;
		this.countryid = countryid;
		this.regionid = regionid;
		this.name = name;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "countryid", nullable = false)
	public long getCountryid() {
		return this.countryid;
	}

	public void setCountryid(long countryid) {
		this.countryid = countryid;
	}

	@Column(name = "regionid", nullable = false)
	public long getRegionid() {
		return this.regionid;
	}

	public void setRegionid(long regionid) {
		this.regionid = regionid;
	}

	@Column(name = "name", nullable = false, length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
*/
}
