package com.spring.mti.model.address;

// Generated 25.03.2013 20:11:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name = "city")
public class City implements java.io.Serializable {

	private long id;
	private long countryid;
	private long regionid;
	private String name;

	public City() {
	}

	public City(long id, long countryid, long regionid, String name) {
		this.id = id;
		this.countryid = countryid;
		this.regionid = regionid;
		this.name = name;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "countryid", nullable = false)
	public long getCountryid() {
		return this.countryid;
	}

	public void setCountryid(long countryid) {
		this.countryid = countryid;
	}

	@Column(name = "regionid", nullable = false)
	public long getRegionid() {
		return this.regionid;
	}

	public void setRegionid(long regionid) {
		this.regionid = regionid;
	}

	@Column(name = "name", nullable = false, length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
