package com.spring.mti.model.address;

// Generated 25.03.2013 20:11:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.transaction.annotation.Transactional;

import com.sun.istack.internal.NotNull;

/**
 * Region generated by hbm2java
 */
@Entity
@Table(name = "region")
public class Region implements java.io.Serializable {
	@Id
	private long id;
	@NotNull
	private String name;
	@ManyToOne(cascade=CascadeType.REFRESH,fetch=FetchType.EAGER)
	@JoinColumn(name="countryid")
	private Country fk_country;

	public long getId() {
		return id;
	}
	
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public Country getFk_country() {
		return fk_country;
	}
	public void setFk_country(Country fk_country) {
		this.fk_country = fk_country;
	}
	
	/*
	private long countryid;
	private String name;

	public Region() {
	}

	public Region(long id, long countryid, String name) {
		this.id = id;
		this.countryid = countryid;
		this.name = name;
	}


	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "countryid", nullable = false)
	public long getCountryid() {
		return this.countryid;
	}

	public void setCountryid(long countryid) {
		this.countryid = countryid;
	}

	@Column(name = "name", nullable = false, length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
*/
}
